# Generated by Django 5.2.11 on 2026-02-26 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_subject_courseoutcome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='ProfSubject',
        ),
    ]
