# Generated by Django 5.2.12 on 2026-03-29 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_coconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='coconfiguration',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.faculty'),
        ),
    ]
