# Generated by Django 5.2.11 on 2026-04-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_coconfiguration_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttainmentLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=50)),
                ('level1', models.FloatField()),
                ('level2', models.FloatField()),
                ('level3', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
