# Generated by Django 5.2.11 on 2026-02-27 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_student'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('roll_number', 'batch', 'session')},
        ),
    ]
