# Generated by Django 6.0.2 on 2026-04-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_attainmentlevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='POPSO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PO', 'PO'), ('PSO', 'PSO')], max_length=5)),
                ('code', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('branch', models.CharField(max_length=50)),
                ('session', models.CharField(max_length=20)),
            ],
        ),
    ]
