# Generated by Django 5.2.11 on 2026-02-27 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_courseoutcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='COMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_number', models.IntegerField()),
                ('marks', models.FloatField()),
                ('batch', models.CharField(max_length=20)),
                ('session', models.CharField(max_length=20)),
                ('semester', models.IntegerField()),
                ('branch', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
        ),
    ]
