# Generated by Django 6.0.2 on 2026-04-07 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_popso'),
    ]

    operations = [
        migrations.CreateModel(
            name='COPSOMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_mapping', models.JSONField()),
                ('pso_mapping', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courseoutcome')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
        ),
    ]
