# Generated by Django 5.2.12 on 2026-03-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_comark'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoutcome',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
