# Generated by Django 6.0.2 on 2026-04-08 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_copsomap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copsomap',
            name='co',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coconfiguration'),
        ),
    ]
