# Generated by Django 6.0.2 on 2026-04-10 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_copsomap_co'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='copsomap',
            unique_together={('subject', 'co')},
        ),
    ]
