# Generated by Django 5.2.12 on 2026-03-07 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_courseoutcome_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseoutcome',
            old_name='semester',
            new_name='co_number',
        ),
        migrations.RemoveField(
            model_name='courseoutcome',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='courseoutcome',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='courseoutcome',
            name='session',
        ),
        migrations.AddField(
            model_name='courseoutcome',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseoutcome',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_outcomes', to='core.subject'),
        ),
    ]
