# Generated by Django 5.2.12 on 2026-03-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_semester_courseoutcome_co_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseoutcome',
            name='co_number',
        ),
        migrations.RemoveField(
            model_name='courseoutcome',
            name='description',
        ),
        migrations.RemoveField(
            model_name='courseoutcome',
            name='subject',
        ),
        migrations.AddField(
            model_name='courseoutcome',
            name='batch',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='courseoutcome',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courseoutcome',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseoutcome',
            name='session',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
