# Generated by Django 5.2.12 on 2026-03-08 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_courseoutcome_co_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='roll_number',
            new_name='registration_number',
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('registration_number', 'batch', 'session')},
        ),
    ]
