# Generated by Django 5.2.12 on 2026-03-08 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_roll_number_student_registration_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='registration_number',
            new_name='roll_number',
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('roll_number', 'batch', 'session')},
        ),
    ]
